version: "3"
services:
  backend:
    build:
      context: ./backend
      args:
        AAA: 'XXX'
    image: "chenchuk/hasm-backend:1.0"
    ports:
      - 8090:8090
    restart: always

  frontend:
    image: httpd:2.4
    volumes:
      - ${PWD}/website/:/usr/local/apache2/htdocs/
      #- ${PWD}/website/:/usr/local/apache2/website/
    ports:
      - 8888:80
    environment:
      #ASSEMBLER_URL: "http://backend:8090/assemble"
      ASSEMBLER_URL: "http://localhost:8090/assemble"
    depends_on:
      - backend


